# Generated by Django 4.1 on 2023-02-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_remove_objetoventa_vendedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetoventa',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objetoventa',
            name='descripcion',
            field=models.TextField(max_length=300),
        ),
    ]
